resolver: nightly-2020-10-07

packages:
- .

extra-deps:
- github: lucasdicioccio/http2-client
  commit: 7201f65b31bf0a2b0bc4a904173233e1e728697b
- github: haskell-grpc-native/http2-grpc-haskell
  subdirs:
  - http2-client-grpc
  - http2-grpc-proto-lens
  - http2-grpc-types
  commit: 496e92bc967eff02ac3698ba12ba2dfe38bc8b74
- random-1.2.0
- splitmix-0.1.0.1

allow-newer: true
