name: Build
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  linux-cabal:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc: ['8.6.5', '8.8.1']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.0'
    - name: Install protobuf compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    - name: Update package database
      run: |
        cabal v2-update
    - name: Build
      run: |
        cabal v2-build

  linux-stack-lts-14:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install protobuf compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    - name: Install stack
      run: which stack || curl -sSL https://get.haskellstack.org/ | sh
    - name: Install GHC
      run: stack setup
    - name: Build
      run: |
        stack build --fast

  macos-stack-lts-14:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - name: Install protobuf compiler
      run: |
        brew install protobuf
    - name: Install stack
      run: which stack || curl -sSL https://get.haskellstack.org/ | sh
    - name: Install GHC
      run: stack setup
    - name: Build
      run: |
        stack build --fast
