name: Build
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  linux-cabal:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    - name: Build
      run: |
        cabal new-build

  linux-stack-lts-14:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install stack
      run: which stack || curl -sSL https://get.haskellstack.org/ | sh
    - name: Install GHC
      run: stack setup
    - name: Build
      run: |
        stack build --fast

  macos-stack-lts-14:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - name: Install stack
      run: which stack || curl -sSL https://get.haskellstack.org/ | sh
    - name: Install GHC
      run: stack setup
    - name: Build
      run: |
        stack build --fast
