name: Build
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  linux-cabal:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['8.10', '9.0']
      fail-fast: false
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/cache@v2.1.6
      name: Cache ~/.cabal/packages
      with:
        path: ~/.cabal/packages
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-packages
    - uses: actions/cache@v2.1.6
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store
    - uses: actions/cache@v2.1.6
      name: Cache dist-newstyle
      with:
        path: dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-dist-newstyle
    - uses: haskell/actions/setup@v1.2.4
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.0'
    - name: Install protobuf compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    - name: Update package database
      run: |
        cabal v2-update
    - name: Build
      run: |
        cabal v2-build -f examples
    - name: Test
      run: |
        cabal install tasty-discover
        env PATH="$HOME/.cabal/bin:$PATH" cabal test
        cabal v2-test


  linux-stack:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        stack-yaml: ['stack.yaml']
      fail-fast: false
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/cache@v2.1.6
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.stack-yaml }}-stack-home
    - uses: actions/cache@v2.1.6
      name: Cache .stack-work
      with:
        path: .stack-work
        key: ${{ runner.os }}-${{ matrix.stack-yaml }}-stack-work
    - name: Install protobuf compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    - name: Install stack
      run: which stack || curl -sSL https://get.haskellstack.org/ | sh
    - name: Install GHC
      run: stack setup --stack-yaml ${{ matrix.stack-yaml }}
    - name: Build
      run: |
        stack build --flag lightstep-haskell:examples --fast --stack-yaml ${{ matrix.stack-yaml }} --no-interleaved-output
    - name: Test
      run: |
        stack test --fast

  macos-stack:
    runs-on: macOS-latest
    strategy:
      matrix:
        stack-yaml: ['stack.yaml']
      fail-fast: false
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/cache@v2.1.6
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.stack-yaml }}-stack-home
    - uses: actions/cache@v2.1.6
      name: Cache .stack-work
      with:
        path: .stack-work
        key: ${{ runner.os }}-${{ matrix.stack-yaml }}-stack-work
    - name: Install protobuf compiler
      run: |
        brew install protobuf
    - name: Install stack
      run: which stack || curl -sSL https://get.haskellstack.org/ | sh
    - name: Install GHC
      run: stack setup --stack-yaml ${{ matrix.stack-yaml }}
    - name: Build
      run: |
        stack build --flag lightstep-haskell:examples --fast --stack-yaml ${{ matrix.stack-yaml }} --no-interleaved-output
    - name: Test
      run: |
        stack test --fast
